feat(operator): add namespace to grafanaDashboard
k8sgpt-ai/k8sgpt-operator pull request #168
Opened 2023-06-23 00:40 UTC by MateSousa

Closes #138 

## 📑 Description
The `namespace` field has been added to the `grafanaDashboard` section of the `values.yaml` file. This allows the Grafana dashboard to be deployed to a specific namespace, which improves organization and separation of concerns.

## ✅ Checks
- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

2023-06-23 10:21 UTC, arbreezy commented
hey @MateSousa  thanks for the PR and the interest in the project.

I believe we want something similar to what we define in prometheus stanza, whereby if `namespace` is not defined in values.yaml we deploy the Grafana dashboard's CM in the same namespace where we deploy the operator

2023-06-23 12:37 UTC, MateSousa commented
@arbreezy i guess it would be like that, right?

2023-06-26 12:28 UTC, AlexsJones submitted a review, later dismissed

2023-06-28 19:18 UTC, arbreezy requested changes

2023-06-29 01:44 UTC, MateSousa commented on chart/operator/templates/grafana-k8sgpt-dashboard.yaml
> +  namespaceSelector:
Ops, i'm going to fix it

2023-06-29 16:40 UTC, arbreezy approved these changes

2023-06-29 16:44 UTC, arbreezy commented
@MateSousa thank you for your contribution

2023-06-29 16:44 UTC, merged