✨ feat(k8sgpt-rbac.yaml): add new RBAC configuration for k8sgpt operator
k8sgpt-ai/k8sgpt-operator pull request #274
Opened 2023-11-25 01:45 UTC by MateSousa

Closes #259

## 📑 Description

Migrate all RBAC related resources to Helm chart's templates

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

2023-11-26 21:30 UTC, arbreezy requested changes

2023-11-26 21:30 UTC, arbreezy commented on chart/operator/templates/k8sgpt-rbac.yaml
> +  name: {{ include "chart.fullname" . }}-operator-role
I think we need a better naming to designate that this is for K8sGPT workload and not operator related

2023-11-26 21:30 UTC, arbreezy commented on chart/operator/templates/k8sgpt-rbac.yaml
> +  name: {{ include "chart.fullname" . }}-operator-rolebinding
same here regarding naming, suggesting to name it `{{ include "chart.fullname" . }}-k8sgpt`

2023-11-26 21:30 UTC, arbreezy commented on chart/operator/templates/k8sgpt-rbac.yaml
> +---
A generic comment, you should split these K8s resources to different template yaml files

2023-11-26 21:36 UTC, arbreezy commented
@MateSousa you want also to remove the permissions of the operator's cluster [role](https://github.com/k8sgpt-ai/k8sgpt-operator/blob/main/chart/operator/templates/manager-rbac.yaml#L58) cause operator won't manage anymore the k8sgpt's role creation right?

2023-11-30 00:37 UTC, MateSousa commented
> @MateSousa you want also to remove the permissions of the operator's cluster [role](https://github.com/k8sgpt-ai/k8sgpt-operator/blob/main/chart/operator/templates/manager-rbac.yaml?rgh-link-date=2023-11-26T21%3A36%3A12Z#L58) cause operator won't manage anymore the k8sgpt's role creation right?

@arbreezy you're right, i just removed

2024-03-28 00:57 UTC, arbreezy commented
Apologies @MateSousa , I forgot that we didn't merge this PR; overall looks good !

can you please resolve the conflicts and I will test a bit more before we merge it

2024-03-29 21:21 UTC, MateSousa commented
@arbreezy done

2024-03-30 00:08 UTC, arbreezy requested changes
@MateSousa , I think you override an existing functionality here.

2024-03-30 00:11 UTC, arbreezy commented on pkg/resources/k8sgpt.go
> +	deployment, er := GetDeployment(config)
^

2024-04-11 16:04 UTC, arbreezy commented
Hey @MateSousa I am happy to properly resolve the previous conflicts and get this merged.

2024-04-12 11:32 UTC, MateSousa commented
Hey @arbreezy, sorry for delay, I was sick... I'm going to fix that today.

2024-04-15 20:14 UTC, arbreezy commented
> Hey @arbreezy, sorry for delay, I was sick... I'm going to fix that today.

@MateSousa hope you are feeling better !

2024-04-23 20:14 UTC, arbreezy commented
@MateSousa, happy to help with this PR if you don't have time, it's almost ready to be merged

2024-05-02 01:44 UTC, closed without merging

2024-05-02 01:45 UTC, MateSousa commented
@arbreezy hey, it looks like I made a huge mess, I'm going to create a new PR, sorry :(